### PR TITLE
Hotfix/close kicked player socket

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
#### 1. Purpose:

Remove/close player sockets from the lobby on player kick.

#### 2. Implementation:

Send message to the backend on player kick that triggers the `#removePlayer` function, add test for this action as well as tests for `#removePlayer`

#### 4. How to Test:

0. Start app backend and frontend
1. Open a window and select host
2. Open another window, select join, and join the lobby you made in step 1
3. Repeat step 2 with two additional players
4. Start the game
5. Kick one of the players
6. With the remaining two players finish the round
7. Verify that the kicked player does not receive the message with the winner of the round

#### 5. Cleanup
- [x] I've added all TODOs needed
- [x] I've removed all unneeded comments
- [x] I've updated the snapshot tests and checked to make sure they're accurate if they changed
- [x] I've removed all unnecessary `console.log`s

### CODE REVIEW

**Review by zachmmeyer — COMMENTED** [review]
image
On a brand new clone of this branch, this error occurs (even with running the npm installer) unless you run the linter/tests.

Once you do get it running:
image
I am unable to host.
Edit: it actually straight up crashes my browser (Firefox) if I leave it too long on the restart screen.

**Comment by wise-king-sullyman** [comment]
@zachmmeyer This is something I'll have to look into and get back to you. I will try and do so tomorrow.

**Comment by zachmmeyer** [comment]
@wise-king-sullyman This might be another partial instance of a virtual machine causing problems, at least with the latter half. I do not have a way to confirm that right now.

**Comment by wise-king-sullyman** [comment]
@zachmmeyer do you have nosleep.js in your package.json?

**Comment by zachmmeyer** [comment]
> 
> 
> @zachmmeyer do you have nosleep.js in your package.json?

It was there already. It hasn't been added, otherwise it would have shown in git as changed files. It stopped with that error after I ran the linter for whatever reason, but it still won't let me host.

**Review by zachmmeyer — APPROVED** [review]
I can reproduce the nosleep issue, but not the socket error. I don't see a reason to not approve this.

**Review by I3uckwheat — APPROVED** [review]

**Pull request merged**
